### PR TITLE
Genetic algorithms using GeneticSharp

### PR DESCRIPTION
**Pull request by ilyasoulk**
We implemented a first simple version of a genetic algorithm with genes corresponding to a 3x3 grid that only contains a unique value [1..9]

We tried to implement the second approach described in this [article](https://arxiv.org/ftp/arxiv/papers/0805/0805.0697.pdf)

### CODE REVIEW

**Comment by jsboige** [comment]
Bonjour, je prends connaissance de votre PR un peu sur le tard. 
Est-ce que vous pourriez créer un projet dédié comme les autres plutôt que de travailler dans Shared?

**Comment by jsboigeEpita** [comment]
Je vois vos nouveaux commits, mais les fichiers sont toujours au mauvais endroit. Est-ce que vous pouvez corriger ça en créant un projet dédié?

**Comment by ilyasoulk** [comment]
> Je vois vos nouveaux commits, mais les fichiers sont toujours au mauvais endroit. Est-ce que vous pouvez corriger ça en créant un projet dédié?

Bonjour, c'est fait!

**Comment by SinnnwL** [comment]
Implementation of the Genetic Algorithm to solve a Sudoku:

** What this PR does: **
- Cleans the Sudoku by filling everything 'obvious' cases that can be guessed with Inferences rules
- Output a Mask representing every possibles values for each cases
- Uses the Genetic Implementation with a genome of 9 chromosomes representing each row
- Uses 2 different methods to generate the Genes : 
   1. Generate Random Genes Based on The Possibles Values Given By The Mask
   2. Generate Genes Based on Their Probability Based on the Number of Possibilities for each Cases

** Good To Know: **
- The Sudoku works for the 6 first easy mostly thanks to the clean. And almost works for the 7th (Fitness of 1/2 => 1 Errors found)
- Some implementations idea were not pushed because unsucessful (Compute 8 genes instead on 9 to reduce the possibilityand guess the last one at the end, Fitness Tabou, etc..)

**Comment by ilyasoulk** [comment]
> Implementation of the Genetic Algorithm to solve a Sudoku:
> 
> **What this PR does:**
> 
> * Cleans the Sudoku by filling everything 'obvious' cases that can be guessed with Inferences rules
> * Output a Mask representing every possibles values for each cases
> * Uses the Genetic Implementation with a genome of 9 chromosomes representing each row
> * Uses 2 different methods to generate the Genes :
>   
>   1. Generate Random Genes Based on The Possibles Values Given By The Mask
>   2. Generate Genes Based on Their Probability (Check  the Number of Possibles Values for each Cases)
> 
> **Good To Know:**
> 
> * The Sudoku works for the 6 first easy mostly thanks to the cleaning. And almost works for the 7th (Fitness of 1/2 => 1 Errors found)
> * Some implementations ideas were not pushed because unsuccessful (Compute 8 genes instead on 9 to reduce the possibilities and guess the last one at the end, Fitness Tabou, etc..)
> 
> @jsboigeEpita @jsboige

We also tried to implement the same ideas described in the articles you linked us in the subject description.
**What we also tried** :
- 3x3 genes that respect the box rule of sudokus at initialization.
- Override GeneticSharp mutation : Swap mutation inside 3x3 genes. We take 2 unfix points in the respective gene and swap them if allowed.
- Implemented a mutation with a probability depending on the current fitness. The better the fitness is, the lower is the probability.

**Comment by jsboigeEpita** [comment]
OK pour votre implémentation fonctionnelle pour les Sudokus simples. Ceci dit, a priori la même lib permet d'obtenir de meilleurs résultats. Pouvez-vous comparer vos travaux avec ceux du [code suivant](https://www.dropbox.com/scl/fi/mbyhcf2jq45woxv9d0io9/Sudoku.GeneticSharp.zip?rlkey=n9s53cecejcpqewahzla95mno&dl=0)?

**Pull request merged**
